### ISSUE TITLE
Top plates and soldering order/switch position

### ISSUE THREAD

**Issue by jsribeiro** [SamGowland/Gowla-Macro-Boards#5]
Hi!

Just got one of the PCBs and it looks great! Very well built and great finish.

I just have a doubt regarding key switch positions when using a top plate. From pictures, and from what makes more sense, the switches are placed above the top plate. This way the spacing is perfect and the plate takes on the weight of the key presses.

However, I can't seem to find a way to make this happen. Since I need to 1) solder at least one of the switches in order to 2) solder the Pro Micro, if I place the switch above the plate, I won't be able to solder the Pro Micro.

Should the plate go over the switches, then? If so, are the 2mm spacers included in the package the correct length?

Or am I thinking the wrong way about something? :)

Thanks!

**Comment by SamGowland** [comment]
Hi :)

This depends if you have a normal or eRGB. 

Normal (v1) top plate is purely decorative and can be added on to existing builds. Just by removing key caps and sliding over. 

eRGB top plate is functional as well, it will hold plate mount switches and _so the build process is different_. 

Following the instructions for eRGB take note of the fact you solder the _headers of the pro micro first_, then switches and then pro micro otherwise like you have said you will be unable to solder if this is done out of order. 

Hope this helps.

**Comment by jsribeiro** [comment]
Ohhhh...

Even though I have a regular one, it slipped my mind to solder just the Pro Micro headers, because I had already soldered them to the Pro Micro (which I was already using in a breadboard for other stuff).

So yes, it's obvious now... Solder the headers, then solder the switches with the top plate underneath, and finally solder the Pro Micro to the headers...

Thanks... I feel dumb, now... :)

**Comment by SamGowland** [comment]
Yes that's the best way :) you may find you have to snip some of the headers if they are too high as well. 

And you can save soldering time by just soldering the required pins for the version of board (3,4,5,7,8,9) for v1. These can be viewed through the gerber or found in the code. But if unsure just solder all pins. 

If you have a built v1, the top plate for that can be added just by pushing over the top with keycaps removed. Depending on how straigt all the switches are you may have to rotate or flip the plate.
