### ISSUE TITLE
OLED on RGB boards

### ISSUE THREAD

**Issue by afonsoguerra** [SamGowland/Gowla-Macro-Boards#8]
Hi,

While one waits for the next board version to be tested, I wonder if there are free pins on the eRGB to install a OLED display to show which layer one is on. From a quick glance I think pins 2 and 3 that should work for the SCK and SDA are busy already,  right?

Since this is implemented successfully in the new version, I just thought I'll ask.

**Comment by SamGowland** [comment]
Hi :) 

Unfortuantely the pins are used, however if you do not use the rotary encoder you could an SPI screen instead of i2c. 

http://www.phreakmonkey.com/2016/01/generic-5-128x64-oled-spi-display-with.html

See this image for which pins are used. Rotary encoder uses 16 and 14, rgb pwm is pin 10 (red connection top left). 

![image](https://user-images.githubusercontent.com/10119462/118689920-6d1b9600-b7ff-11eb-87b9-275d6caf2d4c.png)

Kind Regards

**Comment by afonsoguerra** [comment]
Thanks! I'm loving the rotary encoder though... I'll probably just colour-code the underglow then. Thanks for confirming that.
